[package]
name = "armature"
edition = "2024"
version = "0.0.1"

[dependencies]
multicoin = { git = "https://github.com/Algorithmic-Warfare/multicoin", subdir = "packages/multicoin", rev = "c7a97f2f42ffbddbe2d44686cbc9eebd1810b8d6" }

[environments]
testnet_wip = "0x6f993d7a6fe02bcc2ae077d2a8f71d62613e84900fc130c47232514cb5374ab4"
