[package]
name = "armature_world_bridge"
edition = "2024"
version = "0.0.1"

[dependencies]
armature = { local = "../armature_framework" }
world = { local = "../../.world-contracts/contracts/world" }

[environments]
testnet_internal = "4c78adac"
